# Cardinaliteit hasPart/hasConnection (vanuit GWSW_Lijsten Relaties) (20250221)

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
PREFIX : <http://data.gwsw.nl/1.6/totaal/>

SELECT DISTINCT ?OwnerOfProperty ?labelOwner ?Property ?Object ?labelObject ?card ?at

FROM <http://www.ontotext.com/explicit> # GraphDB: gebruik alleen expliciete (not-inferred) binnen default Graph

where
{
 BIND (str(iri(:)) AS ?aft)


 { # zoek de restricties op cardinaliteit
    ?Class1 rdfs:subClassOf ?b .
    ?b ?prd ?at .
    FILTER (CONTAINS(str(?prd), "Cardinality"))
    BIND (IF (CONTAINS(str(?prd), "maxQual"), "max", (IF (CONTAINS(str(?prd), "minQual"), "min", "exact"))) as ?card)
    ?b owl:onProperty ?property .
    ?b owl:onClass ?object . 
    BIND (strafter(str(?property), ?aft) AS ?Property) 
 } 
 UNION {
    ?Class1 rdfs:subClassOf ?b .
    ?b owl:onProperty gwsw:functie .
    ?b owl:hasValue ?object .
    BIND ("functie" as ?Property)
    BIND ("" as ?card) 
    BIND ("" as ?at) 
 }
 ?Class1 rdfs:label ?labelOwner .
 FILTER (lang(?labelOwner) != "en")

 ?object rdfs:label ?labelObject .
 FILTER (lang(?labelObject) != "en")

 #?Class2 rdfs:subClassOf* ?Class1 . # Property path: 0 of meer links
 #?Class2 :hasDateStart ?dat . # alleen GWSW-classes gebruiken
 #FILTER (CONTAINS(str(?Class2), ?aft))
 
 BIND (strafter(str(?Class1), ?aft) AS ?OwnerOfProperty)
 # BIND (strafter(str(?Class2), ?aft) AS ?Subject)
 BIND (strafter(str(?object), ?aft) AS ?Object)

}
